version: '3'
services:
  shedlandauth:
    depends_on:
      - mongodb
    build: .
    volumes:
      - .:/shedlandauth
    ports:
      - '8180:8000'
    environment:
      - TZ=Europe/London

  mongodb:
    image: mongo:6-jammy
    ports:
      - '27002:27017'
    volumes:
      - dbdata1:/data/db
    restart: on-failure

volumes:
  dbdata1: